baseUrl=https://web-cdn.api.bbci.co.uk/wc-poll-data/container/sport-standings
queryValid=urn:bbc:sportsdata:rugby-union:tournament:six-nations
queryAnotherCompetitionName=urn:bbc:sportsdata:rugby-union:tournament:world-cup
queryInvalid=urn:bbc:sportsdata:rugby-union:tournament:BBC-cup
